[workspace]
members = [
    "crates/filament",
    "crates/filament-cli",
    "crates/filament-core",
    "crates/filament-parser",
]
default-members = ["crates/filament-cli"]
resolver = "3"

[workspace.package]
version = "0.1.0"
edition = "2024"
authors = ["Foad Nosrati Habibi"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/foadnh/filament"
