[package]
name = "filament"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.40", features = ["derive"] }
color = "0.3.1"
env_logger = { version = "0.11.8", features = ["kv"] }
layout-rs = "0.1.3"
lazy_static = "1.5.0"
log = { version = "0.4.27", features = ["kv", "kv_std"] }
miette = { version = "7.6.0", features = ["fancy"] }
thiserror = "2.0.12"
petgraph = "0.8.2"
svg = "0.18.0"
cosmic-text = "0.14.2"
rand = "0.9.1"
rust-sugiyama = "0.3.0"
toml = "0.8.23"
serde = { version = "1.0", features = ["derive"] }
directories = "6.0.0"
winnow = "0.7.12"
