[package]
name = "filament"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.37", features = ["derive"] }
color = "0.2.3"
env_logger = { version = "0.11.8", features = ["kv"] }
layout-rs = "0.1.3"
log = { version = "0.4.27", features = ["kv", "kv_std"] }
nom = "8.0.0"
nom_locate = "5.0.0"
miette = { version = "7.5.0", features = ["fancy"] }
thiserror = "2.0.12"
petgraph = "0.7.1"
svg = "0.18.0"
